version: '3.4'

services:
  ticketapi.api:
    image: ${DOCKER_REGISTRY-}ticketapiapi
    build:
      context: .
      dockerfile: src/Ticket/TicketApi.Api/Dockerfile

  paymentapi.api:
    image: ${DOCKER_REGISTRY-}paymentapiapi
    build:
      context: .
      dockerfile: src/Payment/PaymentApi.Api/Dockerfile

  notificationapi.api:
    image: ${DOCKER_REGISTRY-}notificationapiapi
    build:
      context: .
      dockerfile: src/Notfication/NotificationApi.Api/Dockerfile

  bookapi.api:
    image: ${DOCKER_REGISTRY-}bookapiapi
    build:
      context: .
      dockerfile: src/Book/BookApi.Api/Dockerfile  
      
  eventease.web:
    image: ${DOCKER_REGISTRY-}eventeaseweb
    build:
      context: .
      dockerfile: src/Web/EventEase.Web/Dockerfile  

  eventease.angular.app:
    container_name: flight-horizon-angular-client
    build:
     context: ./src/Web/EventEase.Web/ClientApp
     dockerfile: Dockerfile.develop
    ports:
     - "4200:4200"  # Map container port 4200 to host port 4700
    volumes:
    - ./src/Web/EventEase.Web/ClientApp:/usr/src/app
    - /usr/src/app/node_modules
    command: ["ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]

